# Generated by Django 4.2.5 on 2023-10-03 22:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('intro', models.TextField()),
                ('content', models.TextField()),
                ('schedule', models.DateTimeField()),
                ('template', models.CharField(max_length=50)),
                ('ticket', models.URLField()),
            ],
            options={
                'verbose_name': 'Event',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventTypeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Event Type',
                'db_table': 'event_type',
            },
        ),
        migrations.CreateModel(
            name='SpeakerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('tagline', models.TextField()),
                ('intro', models.TextField()),
                ('img', models.ImageField(upload_to='team')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('x', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Speaker',
                'db_table': 'speaker',
            },
        ),
        migrations.CreateModel(
            name='SponsorsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='sponsor')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'db_table': 'sponsors',
            },
        ),
        migrations.CreateModel(
            name='VenueModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=70)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Venue',
                'db_table': 'venue',
            },
        ),
        migrations.CreateModel(
            name='VolunteerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('tagline', models.TextField()),
                ('intro', models.TextField()),
                ('img', models.ImageField(upload_to='team')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('x', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Volunteer',
                'db_table': 'volunteer',
            },
        ),
        migrations.CreateModel(
            name='VenueImagesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='venue')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_images', to='app.venuemodel')),
            ],
            options={
                'verbose_name': 'Venue Image',
                'db_table': 'venue_images',
            },
        ),
        migrations.CreateModel(
            name='EventScheduleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('topic_info', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_schedule_item', to='app.eventmodel')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers_slot', to='app.speakermodel')),
            ],
            options={
                'verbose_name': 'Schedule',
                'db_table': 'schedule',
            },
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='sponsors',
            field=models.ManyToManyField(to='app.sponsorsmodel'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='team',
            field=models.ManyToManyField(to='app.volunteermodel'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_venue', to='app.venuemodel'),
        ),
    ]
